baseURL: https://blog.charliie.dev
languageCode: en-us
title: Charles Chiu
theme: "PaperMod"
paginate: 3
author:
  name: "Charles Chiu"
  url: "https://github.com/CharlesChiuGit"
  avatar: "charliie_unicorn.png"

params:
  env: production
  googleAnalytics: "G-0YYDW2B6FM"
  sitemap:
    changefreq: hourly
    filename: sitemap.xml
    priority: 0.5
  # homeInfoParams:
  #   Title: Sup bruh 😎
  #   Content: HipHop enthusiast, PKM learner and  Coffee addict.

  profileMode:
    enabled: true
    title: "Sup bruh 😎"
    subtitle: "HipHop enthusiast, PKM learner and  Coffee addict."
    imageUrl: "https://img.charliie.dev/unicorn.png"
    imageWidth: 240 # custom size
    imageHeight: 240 # custom size
    buttons:
      - name: Search
        url: "/search/"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/CharlesChiuGit"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/UCn1_M9mn14YZvBVgChbsYlA"
    - name: "twitter"
      url: "https://twitter.com/charliie_dev"
    # - name: "medium"
    #   url: "https://medium.com/@charlie_chiu_"
    # - name: "matters"
    #   url: "https://matters.news/@charliie"
    - name: "kofi"
      url: "https://buymeacoffee.com/charleschiu"
    - name: "email"
      url: "mailto:mail@charliie.dev"
    - name: "rss"
      url: "https://blog.charliie.dev/index.xml"
  ShowReadingTime: true
  author: "Charles Chiu"
  contact: "mail@charliie.dev"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Logseq](https://logseq.com/)."
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  canonifyURLs: true
  favicon: "favicon.ico"
  icon: "unicorn.ico"
  image: "unicorn.ico"
  busuanzi:
    enable: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
